### ISSUE TITLE
White theme users

### ISSUE THREAD

**Issue by MathiDEV** [socialeonet/Abricot-Tests#1]
![image](https://user-images.githubusercontent.com/40570499/159067413-4560b4a3-0889-42d0-aad9-27a2f137a7cb.png)

**Comment by Fyroeo** [comment]
@MathiDEV Unfortunately, Github doesn't provide any way to know if the user is using the white or dark theme. Additionally, our logo artist did not provide a logo which might work in the two ways.

Therefore, I'm not able to provide a fix for the issue, and I'm marking it as closed
